//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace B2B_Web_Form
{
    using System;
    using System.Collections.Generic;
    
    public partial class templates_storage
    {
        public int id { get; set; }
        public string name { get; set; }
        public string folder_path { get; set; }
        public string file_name { get; set; }
    }
}
