//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class apa_supportEntities : DbContext
    {
        public apa_supportEntities()
            : base("name=apa_supportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<airline> airline { get; set; }
        public virtual DbSet<airports> airports { get; set; }
        public virtual DbSet<cities> cities { get; set; }
        public virtual DbSet<contributors_type> contributors_type { get; set; }
        public virtual DbSet<roundtrip> roundtrip { get; set; }
        public virtual DbSet<search_result> search_result { get; set; }
        public virtual DbSet<service_class> service_class { get; set; }
        public virtual DbSet<stops> stops { get; set; }
        public virtual DbSet<templates_storage> templates_storage { get; set; }
    }
}
