//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class apa_dbModel : DbContext
    {
        public apa_dbModel()
            : base("name=apa_dbModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<airline> airline { get; set; }
        public DbSet<airports> airports { get; set; }
        public DbSet<cities> cities { get; set; }
        public DbSet<contributors_type> contributors_type { get; set; }
        public DbSet<roundtrip> roundtrip { get; set; }
        public DbSet<search_result> search_result { get; set; }
        public DbSet<service_class> service_class { get; set; }
        public DbSet<stops> stops { get; set; }
        public DbSet<templates_storage> templates_storage { get; set; }
    }
}
