//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class b2b_supportEntities1 : DbContext
    {
        public b2b_supportEntities1()
            : base("name=b2b_supportEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<airline> airline { get; set; }
        public virtual DbSet<airports> airports { get; set; }
        public virtual DbSet<cities> cities { get; set; }
        public virtual DbSet<contributors_type> contributors_type { get; set; }
        public virtual DbSet<roundtrip> roundtrip { get; set; }
        public virtual DbSet<search_result> search_result { get; set; }
        public virtual DbSet<service_class> service_class { get; set; }
        public virtual DbSet<stops> stops { get; set; }
        public virtual DbSet<templates_storage> templates_storage { get; set; }
    }
}
