//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class cities
    {
        public string iata { get; set; }
        public string name { get; set; }
        public string coordinates { get; set; }
        public string timezone { get; set; }
        public string parent_name { get; set; }
    }
}
