//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class contributors_type
    {
        public contributors_type()
        {
            this.search_result = new HashSet<search_result>();
        }
    
        public int id { get; set; }
        public string type { get; set; }
    
        public virtual ICollection<search_result> search_result { get; set; }
    }
}
