//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class service_class
    {
        public service_class()
        {
            this.roundtrip = new HashSet<roundtrip>();
            this.search_result = new HashSet<search_result>();
        }
    
        public int Id { get; set; }
        public string serviceClass_name { get; set; }
    
        public virtual ICollection<roundtrip> roundtrip { get; set; }
        public virtual ICollection<search_result> search_result { get; set; }
    }
}
