//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class stops
    {
        public int Id { get; set; }
        public int search_id { get; set; }
        public string arrival { get; set; }
        public System.DateTime arr_date { get; set; }
        public System.TimeSpan arr_time { get; set; }
        public string operate_carrier { get; set; }
        public Nullable<int> operateFlight_number { get; set; }
        public string departure { get; set; }
        public System.DateTime dep_date { get; set; }
        public System.TimeSpan dep_time { get; set; }
        public bool roundtrip_leg { get; set; }
    
        public virtual search_result search_result { get; set; }
    }
}
