//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class stops
    {
        public int Id { get; set; }
        public int search_id { get; set; }
        public string arrival { get; set; }
        public System.DateTime arr_date { get; set; }
        public System.TimeSpan arr_time { get; set; }
        public string operate_carrier { get; set; }
        public Nullable<int> operateFlight_number { get; set; }
        public string departure { get; set; }
        public System.DateTime dep_date { get; set; }
        public System.TimeSpan dep_time { get; set; }
        public bool roundtrip_leg { get; set; }
    
        public virtual search_result search_result { get; set; }
    }
}
